
project_id = "hobeqfidtdrqvjuomcxl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://hobeqfidtdrqvjuomcxl.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_hashing = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.process-agent-package]
verify_jwt = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
