// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hobeqfidtdrqvjuomcxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYmVxZmlkdGRycXZqdW9tY3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDU5NDQsImV4cCI6MjA2NjUyMTk0NH0.jYq7s7GCR1unlzuD9tqTIzb65RAqFgOUe2EIxtFDels";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);